# Generated by Django 3.2.9 on 2022-01-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='re_order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='threshold',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='made_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
