# Generated by Django 3.2.9 on 2022-02-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
