# Generated by Django 3.2.9 on 2022-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20220204_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='re_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='threshold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
