# Generated by Django 3.2.9 on 2022-02-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
