# Generated by Django 3.2.9 on 2022-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='restock',
            field=models.BooleanField(default=False),
        ),
    ]
