# Generated by Django 3.2.9 on 2022-02-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_purchase_restock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='restock',
        ),
    ]
