# Generated by Django 3.2.9 on 2022-03-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='made_stock',
        ),
    ]
