# Generated by Django 3.2.9 on 2022-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_item',
            field=models.BooleanField(default=True),
        ),
    ]
