# Generated by Django 3.2.9 on 2022-04-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_basket_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='delete',
        ),
    ]
