# Generated by Django 3.2.9 on 2022-04-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20220421_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.basket')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ordernumber')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
