# Generated by Django 3.2.9 on 2022-04-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20220421_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordernumber',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='menu_item_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.menuitem'),
        ),
    ]
