# Generated by Django 3.2.9 on 2022-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_auto_20220422_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='menu_item_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
