# Generated by Django 3.2.9 on 2022-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_purchase_menu_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='order',
            name='ingredient_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
