# Generated by Django 3.2.9 on 2022-04-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_table_tableorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['menu_item_name']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_num']},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='purchase',
            name='table_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.tableorder'),
        ),
    ]
