# Generated by Django 3.2.9 on 2022-04-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_auto_20220426_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='table_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.tableorder'),
        ),
    ]
