# Generated by Django 3.2.9 on 2022-04-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_purchase_table_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='kanban',
            field=models.BooleanField(default=False, verbose_name='Reorder'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='re_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reorder Quantity'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='threshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reorder Threshold'),
        ),
    ]
